### ISSUE TITLE
os1.0.6.0，安卓14启动闪退

### ISSUE THREAD

**Issue by Elegantttt** [qhy040404/FxxkMIUIAd#1]
java.lang.RuntimeException: Unable to start activity ComponentInfo{com.qhy040404.fxxkmiuiad/com.qhy040404.fxxkmiuiad.MainActivity}: java.lang.IllegalStateException: No Binding type argument found.
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3987)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:4140)
	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:103)
	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:149)
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:99)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2585)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loopOnce(Looper.java:224)
	at android.os.Looper.loop(Looper.java:318)
	at android.app.ActivityThread.main(ActivityThread.java:8744)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:561)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1013)
Caused by: java.lang.IllegalStateException: No Binding type argument found.
	at com.qhy040404.fxxkmiuiad.Z5$a.b(Unknown Source:41)
	at com.qhy040404.fxxkmiuiad.q1.W(Unknown Source:0)
	at com.qhy040404.fxxkmiuiad.q1.onCreate(Unknown Source:7)
	at android.app.Activity.performCreate(Activity.java:8891)
	at android.app.Activity.performCreate(Activity.java:8856)
	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1468)
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3969)
	... 12 more

**Comment by qhy040404** [comment]
[1.2.1](https://github.com/qhy040404/FxxkMIUIAd/releases/tag/1.2.1) 已发布，修复了这个bug

**Comment by Elegantttt** [comment]
> [1.2.1](https://github.com/qhy040404/FxxkMIUIAd/releases/tag/1.2.1) 已发布，修复了这个bug

thanks a lot
